[package]
name = "fdedup"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.10.6"
walkdir = "2"

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
lto = "fat"
opt-level = 3
panic = "abort"
rpath = false
strip = true
