[package]
name = "fdedup"
version = "0.1.1"
edition = "2021"
authors = ["Massimo Fasciano"]

[dependencies]
sha2 = "0.10.6"
walkdir = "2"
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"
clap = { version = "4.1.6", features = ["derive"] }

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
lto = "fat"
opt-level = 3
panic = "abort"
rpath = false
strip = true

[features]
default = ["verbose"]
verbose = []
